#!/bin/bash

#	This config runs indel realignment steps only. Please see "Config" file for full pipeline.
#   More complete information on how to fill out
#       this Config file can be found at:
#       https://github.com/MorrellLAB/sequence_handling/wiki/Configuration

###################################################
##########     Shared across handlers    ##########
###################################################

#   Where are we storing the output files?
#       Final directory is ${OUT_DIR}/Name_of_Handler
OUT_DIR=/panfs/roc/groups/9/morrellp/shared/Datasets/Alignments/barley_outgroups

#   Name this project
PROJECT=murinum

#   What email should we use for job notifications?
EMAIL=liux1299@umn.edu

#   What encoding is used for quality values?
#       Look at the FastQC files to determine
#       the sequence encoding. Choose from:
#           'sanger', 'illumina'
#           'solexa', or 'phred'
QUAL_ENCODING=sanger

#   Sequencing platform technology
#       What platform were the reads produced?
#       Valid options are:
#           CAPILLARY, LS454, ILLUMINA,
#           SOLID, HELICOS, IONTORRENT
#           ONT, and PACBIO
SEQ_PLATFORM=ILLUMINA

#   What reference genome are we using?
#       Include the full file path.
REF_GEN=/panfs/roc/groups/9/morrellp/shared/References/Reference_Sequences/Barley/Morex_v3/Barley_MorexV3_pseudomolecules_parts.fasta

#   Is this organism barley?
#       Choose from: "true" or "false"
BARLEY="true"

#   Are you running the analysis on the Minnesota Supercomputing Institute (MSI)?
#       Choose from: "true" or "false"
MSI="true"

#   Are you submitting the job with qsub from PBS (Portable Batch System)
#       Choose from: "true" or "false"
USE_PBS="false"

#   Are you submitting the job with sbatch from Slurm?
#       Choose from: "true" or "false"
USE_SLURM="true"

#   Do the quality scores need to be adjusted for GATK? Default: false
#       Change to true if you get errors from GATK like:
#       "<Sample> appears to be using the wrong encoding for quality scores: we encountered an extremely high quality score"
FIX_QUALITY_SCORES=false

#   Where should Picard/GATK store temporary files?
#       If you've encountered issues with running out of temp space
#           with picard, you can optionally specify a temp directory
#       Otherwise, leave blank
TMP=/scratch.global/liux1299/outgroups-temp

############################################
########  Realigner_Target_Creator  ########
############################################

#   Which queue are we submitting the job to?
#   Note: For USE_PBS, we can only specify one queue
#         For USE_SLURM, we can specify multiple queues that are comma separated, no spaces (e.g., "small,ram256g,ram1t")
RTC_QUEUE="small,ram256g,ram1t"

#   USE_SLURM: What are our sbatch settings for Variant_Filtering?
#       Below are the recommended settings
RTC_SBATCH="--nodes=1 --ntasks-per-node=16 --mem=12gb --tmp=10gb -t 06:00:00 --mail-type=ALL --mail-user=${EMAIL} -p ${RTC_QUEUE}"

#   Where is the list of finished BAM files?
#       To generate this list, use sample_list_generator.sh
#       located at /sequence_handling/HelperScripts/sample_list_generator.sh
RTC_BAM_LIST=/scratch.global/liux1299/barley_outgroups/merged_bam/murinum_bam_list.txt

############################################
#########     Indel_Realigner      #########
############################################

#   Which queue are we submitting the job to?
#   Note: For USE_PBS, we can only specify one queue
#         For USE_SLURM, we can specify multiple queues that are comma separated, no spaces (e.g., "small,ram256g,ram1t")
IR_QUEUE="small,ram256g,ram1t"

#   USE_SLURM: What are our sbatch settings for Variant_Filtering?
#       Below are the recommended settings
IR_SBATCH="--nodes=1 --ntasks-per-node=8 --mem=32gb --tmp=30gb -t 42:00:00 --mail-type=ALL --mail-user=${EMAIL} -p ${IR_QUEUE}"

#   Where is the list of finished BAM files?
#       To generate this list, use sample_list_generator.sh
#       located at /sequence_handling/HelperScripts/sample_list_generator.sh
IR_BAM_LIST=/scratch.global/liux1299/barley_outgroups/merged_bam/murinum_bam_list.txt

#   Where is the list of realigner targets files (.intervals)?
#       To generate this list, use sample_list_generator.sh
#       located at /sequence_handling/HelperScripts/sample_list_generator.sh
IR_TARGETS=/panfs/roc/groups/9/morrellp/shared/Datasets/Alignments/barley_outgroups/Realigner_Target_Creator/rtc_murinum_list.txt

#   IR_BAM_LIST and IR_TARGETS must have the same sample order.

#   What is the LOD threshold above which the cleaner will clean?
#       GATK default: 5.0, Barley: 3.0
LOD_THRESHOLD=3.0

#   What is the percentage of mismatches at a locus to be considered having high entropy (0.0 < entropy <= 1.0)?
#       GATK default: 0.15, Barley: 0.10
ENTROPY_THRESHOLD=0.10

#   What is the maximum reads allowed to be kept in memory at a time by the SAMFileWriter?
#       If you are running into memory issues, try reducing this number.
#   Default: 150000
MAX_READS_IN_MEM=5000

############################################
##########      Dependencies      ##########
############################################

#   This section defines installations to
#       various dependencies for sequence_handling.
#   If you are using the Minnesota Supercomputing Institute cluster
#       then uncomment all 'module load' lines.
#       Make sure you have access to all '_ML' modules.
#   If you need to install a dependency from source,
#       then uncomment the lines for the dependency and the
#       'export PATH=', and write the full path to the executable
#       for the program. For example:
#       PARALLEL=${HOME}/software/parallel-20151122/bin/parallel
#   If you have a system-wide installation for a program, you can
#       leave all lines commented out. sequence_handling will find
#       system-wide installed programs automatically.

#   Please visit https://github.com/MorrellLab/sequence_handling/wiki/Dependencies
#       for information on version requirements and compatibility

if [[ "$MSI" == "true" ]] ; then
#   Do we have GNU parallel installed
module load parallel/20190122
#PARALLEL=
#export PATH=${PARALLEL}:${PATH}

#   Do we have Java installed?
module load java/openjdk-8_202
#JAVA=
#export PATH=${JAVA}:${PATH}

#   What is the full file path for the GATK jar file?
#   You need BOTH the jar file and the module
#   NOTE: Indel realignment functionality is not in GATK v4. Please use GATK v3.
GATK_JAR=/panfs/roc/groups/9/morrellp/public/Software/GATK_ML_3.8.1-0-gf15c1c3ef/GenomeAnalysisTK.jar
module load gatk_ML/3.8.1

#   What is the full file path for the Picard jar file?
PICARD_JAR=/home/morrellp/public/Software/picard_ML_2.20.2/picard.jar
fi
