#!/usr/bin/env bash

#PBS -l mem=22gb,nodes=1:ppn=16,walltime=24:00:00
#PBS -m abe
#PBS -M liux1299@umn.edu
#PBS -q lab

set -e
set -o pipefail

#   Dependencies
module load parallel
module load samtools_ML/1.3.1

#   User provided arguments
FIX_BAM_HEADER_SCRIPT=/home/morrellp/liux1299/GitHub/Barley_Outgroups/fixBAMHeader.sh
TABLE=/home/morrellp/liux1299/scratch/outgroups/reheader_bam/bam_reheader_table.txt
PLATFORM=ILLUMINA
SAMPLE_LIST=/home/morrellp/liux1299/scratch/outgroups/SAM_Processing/Picard/murinum_bam_list_0.03.txt
OUT_DIR=/home/morrellp/liux1299/scratch/outgroups/reheader_bam

#   Run program
"${FIX_BAM_HEADER_SCRIPT}" -t "${TABLE}" \
                           -p "${PLATFORM}" \
                           -s "${SAMPLE_LIST}" \
                           -o "${OUT_DIR}"
